# --- HIBERNATE / JPA PROPERTIES (DEV) ---
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.generate_statistics=true

# --- LOGGING LEVEL (DEV) ---
# Dùng để ghi đè log4j2 qua system property nếu cần
sql.log.level=debug
sql.bind.level=trace
