name: iuhsmrc-compose--mariadb
services:
  mariadb-iot:
    image: mariadb:11
    container_name: iuhsmrc-mariadb
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MARIADB_DATABASE: smart_room_iot
      MARIADB_ROOT_PASSWORD: 'root'
      TZ: Asia/Ho_Chi_Minh
    healthcheck:
      test: ['CMD', 'healthcheck.sh', '--connect', '--innodb_initialized']
      timeout: 5s
      interval: 10s
      retries: 5
    ports:
      - '3306:3306'
    restart: always
    volumes:
      - ../../local/mariadb_data:/var/lib/mariadb
      - ../scripts/sql/init_table.sql:/docker-entrypoint-initdb.d/01-init_tables.sql:ro
      - ../scripts/sql/init_data.sql:/docker-entrypoint-initdb.d/02-init_data.sql:ro
    networks:
      - default

networks:
  default:
    name: iuhsmrc-network
